### ISSUE TITLE
Auto open with Epic Games Launcher

### ISSUE THREAD

**Issue by Ortieez** [Lasa2/ED-RichPresence#21]
How do I enable the auto launch feature with epic games launcher? Tried searching for something on internet but did not found a solution.

**Comment by VeeLume** [comment]
Turns out its quite tricky to launch ed automaticly from the epic launcher. This should work with the new release:
- Create a desktop shortcut through the epic games launcher
- Put the shortcut wherever you want
- In the app put the shortcut path in the ed path
- Make sure the path ends with .url
![example](https://user-images.githubusercontent.com/23563093/117907686-8096a080-b2d7-11eb-83f7-4e9e005cd217.png)

**Comment by Ortieez** [comment]
Thanks for the reply, I will try it as soon as I can. And then I will share my results if it worked.

**Comment by Ortieez** [comment]
It works, thanks so much!
